name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        **AgentDB will estimate complexity** and recommend implementation approach.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: "I'd like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider?
      placeholder: "I also thought about..."

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require API changes?
      options:
        - No (backward compatible)
        - Yes (breaking change)
        - Unsure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this?
      options:
        - Critical (blocks my project)
        - High (significant impact)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Real-world scenario where this is needed
      placeholder: |
        Example:
        I'm building a knowledge graph app and need...
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Help
      options:
        - label: I'm willing to submit a PR for this
        - label: I can help test this
        - label: I can help with documentation
